### ISSUE TITLE
More specific to-do list for coders?

### ISSUE THREAD

**Issue by TropicSapling** [adri326/rpg-motor#2]
Maybe some more comments as well? Still don't really know how the code works and what to work on

**Comment by adri326** [comment]
True, should we use the github wiki pages feature?

**Comment by adri326** [comment]
So:
- all the images are located in the /ressources folder
- the /ressources folder is organized in themes, the only one for now is the theme basic-16
- in a theme there are the images and the file tiles.json
- the file tiles.json contains the info about every tiles from the theme
- parties are located in the folder /parties/{$party}/
- this folder contains the /map folder and the file setup.json
- the folder /map contains every maps, named by their id
- the file setup.json contains all the info about the party, like what theme to use
- the main code is located at the root directory
- the map creating and the _party creating_ code is in the /create directory
- the file drawMap.js handle the canvas drawing
- the file tilesReader.js handle the compiling and use of the tiles.json file
- the file setupReader handle the loading and the parsing of the setup.json file, the completing of the load of the tiles.json (before parsing it) and the loading of the map.
- the files core.js (they are 2) handle the main part of the code

That's alot, I'll make something cleaner for the readme.md and for the github wiki pages.

**Comment by TropicSapling** [comment]
Well still thanks, it's a lot clearer now :D
Btw yes we should have a wiki for it :)

**Comment by adri326** [comment]
This is the things that have been made for now.

Load of things need to be done though :
- completing the create/createMap.php page (when I'll merge my new branch, because I'm making something in multiple part)
- making the party manager
- making the sessions manager
- preparing the mysql db
- **new tiles**
- the inventory core
- javascript in the setup.json and the map
- map creating tool
- players handler
- entities handler

**Comment by TropicSapling** [comment]
Just some more questions:
- Have you run the first core.js code?
- Should this really be inside of a function?:

```
(function () {
  var requestAnimationFrame = window.requestAnimationFrame || window.mozRequestAnimationFrame || window.webkitRequestAnimationFrame || window.msRequestAnimationFrame;
  window.requestAnimationFrame = requestAnimationFrame;
})();
```

It looks like you might mean the jQuery shorthand (which is $(function() {})) for document.ready?

**Comment by adri326** [comment]
I found this in another canvas-based thingy (http://github.com/herohamp/SlightyPhysics/), it were like this, without JQuery

**Comment by TropicSapling** [comment]
Well in `index.html` you can clearly see it imports jQuery, which I guess means that it works to write without the $. But idk

**Comment by adri326** [comment]
It is here to provide me the ability to draw the frames, I use requestAnimationFrame() at the end of the draw() method in drawMap.js

**Comment by TropicSapling** [comment]
Ik, I just wonder what the function really does. You could just define the variables without a function, unless that's the jQuery function I'm thinking of

**Comment by adri326** [comment]
Yes you can, it should be JQuery at the beginning

**Comment by TropicSapling** [comment]
Oh ok :)
