### ISSUE TITLE
Help : cannot resize the <table>

### ISSUE THREAD

**Issue by adri326** [adri326/rpg-motor#3]
In the createMap-addition branch, I got a problem in the core.js file, where I cannot resize the <table> that allows you to select squares.

The page can be found here : http://adri326.890m.com/rpg/create/createMap.php?width=4&height=4&party=1

At the day I write this issue, I didn't uploaded the last version of the core.js, due to its instability, you'll need to copy-paste it in the navigator's console.

**How my script works?**

It's just a simple Javascript file, that contains some functions and some vars, the functions that interest us is the changeSize() function. It'll look in the two inputs, width and height, get their value, then modify the size of the map variable and the map table _at the same time_.

It can easily resize to lower values, but I can't figure out why it can't resize my <table> to a bigger values, even if it should.

Thanks if you can help me.

**Comment by TropicSapling** [comment]
Hmm idk much about tables but I'll see what I can do :)

**Comment by TropicSapling** [comment]
Exactly what happens when you run the `changeSize()` function? How does the table change, and are there any errors in the console?

**Comment by adri326** [comment]
This function does a lot of things :
- it reduce the y-axis-size of the _map_ array if it should become smaller
- and it deletes every <tr> that should be deleted
- if it should become bigger it adds rows to the _map_ array
- **and it should add rows**
- it reduce each x-axis-size of the rows of the _map_ array if it should become smaller
- and it deletes every <td> that should be deleted
- if it should become bigger it adds colums to the _map_ array
- **it should add columns**

**Comment by TropicSapling** [comment]
Hmm ok

**Comment by adri326** [comment]
http://adri326.890m.com/rpg/create/createMap.php?width=4&height=4&party=1

Still glitchy when changing width and height at the same time

**Comment by adri326** [comment]
Hmm...

**Comment by adri326** [comment]
Tabs are counted as text Element

**Comment by adri326** [comment]
`function actualiseTable() {
  var tbody = editor.childNodes[1];
  trs = [];
  tds = [];
  for (var i = 0; i < tbody.childNodes.length; i++) {
    if (tbody.childNodes[i]+"" != "object Text")
      trs[i] = tbody.childNodes[i];
      tds[i] = [];
      for (var j = 0; j < trs[i].childNodes.length; j++) {
        if (trs[i].childNodes[j]+"" != "object Text") {
          tds[i][j] = trs[i].childNodes[j];
        }
      }
    }
  }
}`

Can't exclude those `#text` objects in the _trs_ array

**Comment by adri326** [comment]
Maybe because I forgot a `{`

**Comment by adri326** [comment]
Now it works

**Comment by TropicSapling** [comment]
Ok great :D
